g=int(input("Введите g "))
p=int(input("Введите p "))
a=int(input("Введите a "))
b=int(input("Введите b "))
A=(g**a)%p
B=(g**b)%p
Ka=(A**b)%p
Kb=(B**a)%p
k=(g**(a*b))%p
print("Ключ A= ", Ka,)
print("Ключ B= ", Kb)
print("Ключ= ", K)
